### ISSUE TITLE
Check what AddressLength property is used for.  Might cause Modbus Polling to Panic

### ISSUE THREAD

**Issue by CanuckMarc** [NubeIO/flow-framework#804]
This error happened when adding a single modbus point.  I think it is an error with AddressLength property.  It may not be required on Modbus points. 

This line: https://github.com/NubeIO/flow-framework/blob/fc25f2ff1986ecf078476943ce553e37769baf65/plugin/nube/protocals/modbus/smod/encoding.go#L65
```
Jan 13 13:11:35 raspberrypi systemd[1]: Starting Flow Framework...
Jan 13 13:11:35 raspberrypi systemd[1]: Started Flow Framework.
Jan 13 13:11:35 raspberrypi flow-framework[16301]: time="2023-01-13T13:11:35+11:00" level=error msg="network Error : dial tcp [::1]:1883: connect: connection refused"
Jan 13 13:11:36 raspberrypi flow-framework[16301]: time="2023-01-13T13:11:36+11:00" level=error msg="network Error : dial tcp [::1]:1883: connect: connection refused"
Jan 13 13:11:36 raspberrypi flow-framework[16301]: time="2023-01-13T13:11:36+11:00" level=info msg="REFRESH TOKEN RUN"
Jan 13 13:11:37 raspberrypi flow-framework[16301]: time="2023-01-13T13:11:37+11:00" level=error msg="username and password combination is incorrect"
Jan 13 13:11:37 raspberrypi flow-framework[16301]: time="2023-01-13T13:11:37+11:00" level=info msg="Started Listening for plain HTTP connection on 0.0.0.0:1660"
Jan 13 13:11:37 raspberrypi flow-framework[16301]: time="2023-01-13T13:11:37+11:00" level=info msg="Create interval histories has been called..."
Jan 13 13:11:37 raspberrypi flow-framework[16301]: time="2023-01-13T13:11:37+11:00" level=info msg="Producer history cleaner has is been called..."
Jan 13 13:11:37 raspberrypi flow-framework[16301]: time="2023-01-13T13:11:37+11:00" level=error msg="record not found"
Jan 13 13:11:37 raspberrypi flow-framework[16301]: time="2023-01-13T13:11:37+11:00" level=info msg="Finished create interval histories process"
Jan 13 13:11:37 raspberrypi flow-framework[16301]: ReadHoldingRegisters()  RESPONSE raw: [195 120]
Jan 13 13:11:37 raspberrypi flow-framework[16301]: panic: runtime error: index out of range [2] with length 2
Jan 13 13:11:37 raspberrypi flow-framework[16301]: goroutine 40 [running]:
Jan 13 13:11:37 raspberrypi flow-framework[16301]: github.com/NubeIO/flow-framework/plugin/nube/protocals/modbus/smod.bytesToUint32s(0x1, 0x2, {0x1888103, 0x2, 0xfd})
Jan 13 13:11:37 raspberrypi flow-framework[16301]:         /home/runner/work/flow-framework/flow-framework/plugin/nube/protocals/modbus/smod/encoding.go:65 +0x30c
Jan 13 13:11:37 raspberrypi flow-framework[16301]: github.com/NubeIO/flow-framework/plugin/nube/protocals/modbus/smod.(*ModbusClient).ReadHoldingRegisters(0x1887960, 0xc55f, 0x1, {0x16d06f8, 0x6})
Jan 13 13:11:37 raspberrypi flow-framework[16301]:         /home/runner/work/flow-framework/flow-framework/plugin/nube/protocals/modbus/smod/modbus.go:203 +0x434
Jan 13 13:11:37 raspberrypi flow-framework[16301]: plugin/unnamed-1ffa745e0b0f9193f827bcc67eb2db1d37fa22b8.(*Instance).networkRead(0x17f37c0, {{0x6224fa58, 0x149c1f0}, 0x1544180, 0x0, 0x1, 0x2, 0x0, 0x0, 0x1, ...}, ...)
Jan 13 13:11:37 raspberrypi flow-framework[16301]:         /home/runner/work/flow-framework/flow-framework/plugin/nube/protocals/modbus/utils.go:286 +0xe98
Jan 13 13:11:37 raspberrypi flow-framework[16301]: plugin/unnamed-1ffa745e0b0f9193f827bcc67eb2db1d37fa22b8.(*Instance).ModbusPolling.func1()
Jan 13 13:11:37 raspberrypi flow-framework[16301]:         /home/runner/work/flow-framework/flow-framework/plugin/nube/protocals/modbus/polling.go:201 +0x196c
Jan 13 13:11:37 raspberrypi flow-framework[16301]: github.com/NubeIO/flow-framework/src/poller.Poller.GoPoll({0x5f5e100}, {0xe1e730, 0x180ab40}, 0x18ab350)
Jan 13 13:11:37 raspberrypi flow-framework[16301]:         /home/runner/work/flow-framework/flow-framework/src/poller/poller.go:69 +0x70
Jan 13 13:11:37 raspberrypi flow-framework[16301]: created by plugin/unnamed-1ffa745e0b0f9193f827bcc67eb2db1d37fa22b8.(*Instance).ModbusPolling
Jan 13 13:11:37 raspberrypi flow-framework[16301]:         /home/runner/work/flow-framework/flow-framework/plugin/nube/protocals/modbus/polling.go:323 +0x1e8
Jan 13 13:11:37 raspberrypi systemd[1]: nubeio-flow-framework.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jan 13 13:11:37 raspberrypi systemd[1]: nubeio-flow-framework.service: Failed with result 'exit-code'.

```

**Comment by CanuckMarc** [comment]
Closed with: https://github.com/NubeIO/flow-framework/pull/807
